[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blossomer-gtm-cli"
version = "0.1.0"
description = "A lightweight CLI tool that demonstrates Blossomer's GTM intelligence"
authors = [
    {name = "Blossomer", email = "hello@blossomer.com"}
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "typer>=0.16.0",
    "rich>=13.9.0", 
    "questionary>=2.1.0",
    "pydantic>=2.0.0",
    "openai>=1.0.0",
    "jinja2>=3.0.0",
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "firecrawl-py>=0.0.16",
    "pyfiglet>=1.0.2"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0"
]

[project.scripts]
blossomer = "cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["cli*", "app*"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"