name: "Email Generation Evaluation"
service:
  module: "app.services.email_generation_service"
  function: "generate_email_campaign_service"
schema: "schema.json"
dataset: "../../datasets/email_eval_enriched.csv"
judges:
  deterministic: ["D-1", "D-2", "D-3", "D-4", "D-5"]
  llm: ["email_quality"]
models:
  default: "OpenAI/gpt-4o-mini"
  fallback: "Gemini/models/gemini-1.5-flash"